apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
