apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:u/eYuSojojYnxTI25gzdzsFzGOkV5EO7NrzNp5sYGYG9xuZG5SVtZSdnlm4WgFTMF6WuNQ3V1S4=,iv:rk2uf/iuMrSKHss7JHcdTziPJmUS1C8L7Mo9UUEijPU=,tag:mMU3yXeahC8oO+bR3DxNGQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-secret
    namespace: renovate
sops:
    age:
        - recipient: age1vr0nnzmg4fjav440a3c3q5c28w88n3htcypukr3nnyckxsphcu9q3tcelz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMXV1YzVLdmVyYzVUQTE1
            VHY2dENSbE1qYUZXNWdMUTJ0RXQwU1ZreVc0Cjdyd0VPMFVKTXRqZ2ZTbzFsU1Br
            aHZORGhCczZwSkdNYmdCWjB2ME1uM28KLS0tIEZ4c0NJZXhEcmtyUEZJNFkzdzV2
            SitDb2RoTVlJZFNoT2lNSnVRYXR1ckEKDZYBi99lViTup6ugCcqS5bycyk1SJPWP
            Kz9jiLe1WSX9xPpd61LShsnlQvKZwoM6naUoqke8D/GSoVNOYKdSJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T18:19:24Z"
    mac: ENC[AES256_GCM,data:IgXDoGU6cnQN+UX1ZKKRUEY2PeMXdM1RdnQwxIUwNzlhDQZKgvoJxvwzvc9wlRMVF7nKmXf3AHhDdEhy0emPCAmvgU267k8/41p3yxRtDl5diwzVSvf9Fv5MbH42gDB1MNaelYKnCmlYF3gehru5nP5rb3DxjRL8F5YaHitbr3M=,iv:O+dWOfBWG+8LAy2fmJ9lN0eclkPO09VhIcnUN7FuclM=,tag:lTzZo7aZeGUN48DWagDU2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
